version: '3.8'

networks:
  lsruleengineapi:
services:
  eventstoredb:
    container_name: eventstoredb
    image: eventstore/eventstore:latest
    volumes:
      - ./certs:/app/certs
      - ./path/on/host:/data/eventstore
    ports:
      - "2113:2113"
      - "1113:1113"
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=True
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=True
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=True
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=True
    networks:
      - lsruleengineapi
  azurecosmos:
    hostname: azurecosmosemulator
    restart: always
    container_name: cosmosdb
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest
    tty: true
    ports:
      - 8081:8081  
      - 8900:8900
      - 8901:8901
      - 8902:8902 
      - 10250:10250
      - 10251:10251
      - 10252:10252
      - 10253:10253
      - 10254:10254
      - 10255:10255
    environment:
      - AZURE_COSMOS_EMULATOR_PARTITION_COUNT=1
      - AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=true
    networks:
      - lsruleengineapi
  ruleengineapi:
    image: ${DOCKER_REGISTRY-}ruleengineapi
    build:
      context: .
      dockerfile: RuleEngineAPI/Dockerfile
    ports:
      - 8001:80
    depends_on: 
      - eventstoredb
      - azurecosmos
    environment:
      - ESDB=esdb://eventstoredb:2113?tls=false&tlsVerifyCert=false
      - ASPNETCORE_ENVIRONMENT=Development
      - COSMOS_ENDPOINT=https://azurecosmosemulator:8081/
    networks:
      - lsruleengineapi
