version: '3.4'
services:
  ruleengineapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # Add connection string/environment variable for EventStoreDB
      - EVENTSTORE_CONNECTION_STRING=eventstoredb:2113
    depends_on:
      - eventstoredb
    volumes:
      - .:/app
      - ~/.nuget/packages:/root/.nuget/packages # Optional: for caching NuGet packages

  eventstoredb:
    image: eventstore/eventstore:latest
    environment:
      EVENTSTORE_CLUSTER_SIZE: 1
      EVENTSTORE_RUN_PROJECTIONS: All
      EVENTSTORE_START_STANDARD_PROJECTIONS: True
      EVENTSTORE_EXT_TCP_PORT: 1113
      EVENTSTORE_HTTP_PORT: "2113"
      EVENTSTORE_INSECURE: True
      EVENTSTORE_ENABLE_EXTERNAL_TCP: True
      EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP: True
    ports:
      - "2113:2113"
      - "1113:1113"

